-- ============================================================
-- Seed: Membership Plans
-- Description: Seed initial membership plans
-- Created: 2026-03-26
-- ============================================================

BEGIN;

-- Insert membership plans
INSERT INTO membership_plans (
    id,
    name,
    slug,
    description,
    price,
    currency,
    duration_days,
    max_contacts_per_day,
    max_photos,
    can_view_contacts,
    can_video_chat,
    can_add_social_links,
    is_ad_free,
    is_featured,
    is_active,
    is_trial,
    trial_days,
    display_order,
    is_recommended,
    benefits,
    created_at,
    updated_at
) VALUES
(
    uuid_generate_v4(),
    'Free',
    'free',
    'Basic membership with limited features',
    0,
    'INR',
    0,
    5,
    3,
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    TRUE,
    FALSE,
    NULL,
    0,
    FALSE,
    '["Basic profile creation", "Limited contacts per day", "Express interest", "Send messages"]'::JSONB,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    uuid_generate_v4(),
    'Silver',
    'silver',
    'Enhanced membership with more features',
    999,
    'INR',
    90,
    10,
    5,
    TRUE,
    FALSE,
    TRUE,
    FALSE,
    FALSE,
    TRUE,
    FALSE,
    NULL,
    1,
    FALSE,
    '["10 contacts per day", "View contact details", "Social media links visible", "Priority support"]'::JSONB,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    uuid_generate_v4(),
    'Gold',
    'gold',
    'Premium membership with video chat',
    2499,
    'INR',
    180,
    25,
    10,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    FALSE,
    NULL,
    2,
    TRUE,
    '["25 contacts per day", "Video chat enabled", "Ad-free experience", "Featured profile", "Horoscope visible", "Priority support"]'::JSONB,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    uuid_generate_v4(),
    'Premium',
    'premium',
    'Full access premium membership',
    4999,
    'INR',
    365,
    50,
    15,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    FALSE,
    NULL,
    3,
    FALSE,
    '["50 contacts per day", "Unlimited messaging", "Video chat enabled", "Ad-free experience", "Featured profile", "Priority support", "Profile highlighting"]'::JSONB,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    uuid_generate_v4(),
    'Diamond',
    'diamond',
    'Ultimate membership with all features',
    9999,
    'INR',
    365,
    NULL, -- Unlimited
    20,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    FALSE,
    NULL,
    4,
    FALSE,
    '["Unlimited contacts", "Unlimited messaging", "Video chat enabled", "Ad-free experience", "Featured profile", "Dedicated support", "Profile highlighting", "Verified badge"]'::JSONB,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
);

COMMIT;
